#!/bin/sh -e

CONFFILE1="/usr/share/zabbix-agent/zabbix_agentd.conf"
CONFFILE_DEST1="/etc/zabbix/zabbix_agentd.conf"

. /usr/share/debconf/confmodule
db_version 2.0 || [ $? -lt 30 ]

if [ "$1" = "configure" ]; then

    RET=""
    db_get zabbix-agent/server || true
    zabbix_server="$RET"
    if [ "$zabbix_server" = "" ]; then
        zabbix_server="localhost"
    fi

    sed "s/^Server=.*/Server=$zabbix_server/g" < $CONFFILE1 | sed "s/^ServerActive=.*/ServerActive=$zabbix_server/g" > $CONFFILE_DEST1.new
    ucf --debconf-ok $CONFFILE_DEST1.new $CONFFILE_DEST1
    rm -f $CONFFILE_DEST1.new

    if ! getent group zabbix > /dev/null 2>&1 ; then
    addgroup --system --quiet zabbix
    fi

    if ! getent passwd zabbix > /dev/null 2>&1 ; then
    adduser --quiet \
        --system --disabled-login --ingroup zabbix \
        --home /var/run/zabbix-server/ --no-create-home \
        zabbix
    fi
    chown zabbix:adm /var/log/zabbix-agent -R
fi

db_stop

#DEBHELPER#

exit 0
